# Workflow for Maven-report content (including Javadoc API) to GitHub Pages
name: Deploy Maven-report to Pages

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:

  build:

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 17
          cache: 'maven'

      - name: Setup Pages
        uses: actions/configure-pages@v3

      - name: Build document with Maven
        run: mvn --show-version --batch-mode site --file pom.xml

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        with:
          # Upload Maven-report repository
          path: './target/site/'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2

### EOF ###
